### ISSUE TITLE
Split releases

### ISSUE THREAD

**Issue by codeliner** [prooph/proophessor#46]
I'd like to start a discussion about the new releases.

We already did a lot of work on various prooph packages to prepare new major releases which make use of PHP 7.1 features and work with changed structure like a reorganized event-store and event-sourcing package, changed structure of prooph messages or a new approach to register prooph/service-bus plugins. A lot of work was done by @prolic many many thanks for that again!

While most of the work for the main packages is done they all miss detailed documentation and migration guides. @prolic started to write migration guides but we need more. The introduced BC breaks make it really hard to upgrade any larger application that makes use of prooph components.

We also have the problem that our framework integration packages for Symfony and Laravel become out-of-date. Upgrade work is in progress thx to @mablae , @UFOMelkor and others but it is still a lot of work needed.

With prooph/micro the situation described above becomes even more problematic. Our first tests, our experience and the wish that prooph becomes a powerful toolbox for event sourced applications pushes all work and energy into prooph/micro and tools around it. It seems that we no longer need all prooph packages to reach our goal. Important packages are prooph/event-store v7, prooph/common and the new *-event-store and snapshot-store packages, message producers, event-store-ui, event-store-http-api and projections.

Not really required for the new approach are all framework integration packages, service-bus, event-sourcing and psr7-middleware and of course the old event-store adapters which will be deprecated anyway.

**The question now is how do we want to deal with it?** We all have limited time and we should spent our time for things that have a future. My current feeling is that prooph/micro has a great future. It is one week old and of course not stable yet but it is already like: "I don't want to look back".

The prooph packages in their current versions are great to work with them in combination with frameworks like zend-expressive, Symfony or Laravel. And I'm sure that this will be the case for the next few years, too. But this does not necessarily mean that we should release new versions for these packages. We can keep them like they are and only work on small improvements and bugfixes. This should be enough IMHO. 

Following this idea we would need a strategy of how to document this and how we want to handle the packages which need new major versions. For example prooph/event-store: We would need a v7 release but also keep the v6 branch active together with the event-store adapters.

Another idea would be that we search and add more maintainers for the various packages so that some of us can focus on prooph/micro and new event-store stuff and others focus on the existing prooph components.

Please tell me what you think about it!

**Comment by prolic** [comment]
I like to put more time into micro.
On ther other hand, I spent too much time in developing these packages, so that I want to publish new major releases, also for event-sourcing and service-bus.
Documentation will follow asap, maybe we can create a roadmap and timeline for the release of prooph-components, as well as we need a roadmap and timeline for micro.

**Comment by prolic** [comment]
Additional thoughts: No everyone will jump on the spaceship to microservices, a lot of people will still build their monoliths. Having f.e. a new service-bus & event-store there available helps to spread prooph and also the new prooph-micro. Also the codebase is battle-tested, tested in production, the new major releases don't change that much on stability, so I don't expect that many required bugfixes. New documentation will steal a little time, that's all.

**Comment by codeliner** [comment]
I see. My problem is that my time is definitely limited. My company requires a lot of time and this situation will not change. A few years ago it was another situation. I had more time for OSS. Now I need to focus on the parts that also add value to the business. We don't get enough attraction with what we have. We have a great community with a lot of excellent developers but the prooph components are way to complex in their current form. Since one year or so we fight against complexity by providing first class support in the chat, in the issues and with proophessor-do(-symfony) but the problem remains. Complexity is caused by logic spread across the various packages and the problem that web framework integration is a pain in the ass. We try to make everything extensible, flexible and clean. 

With prooph/micro we can focus on simplicity. We no longer try to make everyone happy. We show our way of creating (distributed) software with a state-of-the-art toolbox. OOS is always in flux. We should not waste our energy but only focus on the good parts (service-bus etc. are not bad, but no longer required).

I know that we all put a lot of work into the components and also into the new releases, but continious refactoring should not be blocked by work that is done but only by work that needs to be done.

I can only speak for myself here. Maybe we can reorganize the core team and add two or three more maintainers. What do you think @sandrokeil @bweston92 @oqq @basz

**Comment by codeliner** [comment]
@prolic 

> Additional thoughts: Not everyone will jump on the spaceship to microservices, a lot of people will still build their monoliths.

True, but they can do it with the current prooph components. These versions are battle-tested not the new ones!

> the new major releases don't change that much on stability, so I don't expect that many required bugfixes.

I'm not sure about this. service-bus is a complete rewrite for example.
Also the message structure changed. You cannot just upgrade your project. You need to rewrite all your event streams! MongoDb event store is gone, so you need to switch to an alternative. I tried to come up with v7 mongo event store but it is not possible to provide one in a reliable way.

> New documentation will steal a little time, that's all.

Please keep in mind that not only documentation will steal time but also the support in the chat. How can I upgrade? Why does the transaction manager no longer work? ...

Sorry, if I sound a way too hard. I think about it since three month or so. prooph/micro is the result of my thoughts and you transformed it into gold within a few days @prolic ;). That is the speed we need!

**Comment by sandrokeil** [comment]
The current stable releases have LTS. Like @prolic mentioned, new developers maybe not ready for prooph micro and if they want to start with prooph components, it would be better they can use the same versions/structure like prooph micro has, so they can switch later easily.

It would be great if we can find more core developers which focus on a specific theme like Symfony, Laravel, middleware, .... I guess if we *not* support the framework way, we loose many new users and  even some new contributors. We should distungish between new developers (uses prooph for the first time) and developers which uses the current versions of prooph components. I'm not sure, if  latter want to migrate the current project. They can use the new versions in a new project / service / API.

Documentation is hard, but it's a key fact to win or loose. The new versions are almost done, so we should ship them if the docs are ready. If they are bugs for some edge cases, they can bring a PR, that's open source or they can even pay people to fix it. We should find a way to bring the questions from the prooph chat to Stackoverflow. Maybe we create some topics and answers for the major themes on Stackoverflow. I guess this could help to save time and it's more visible for other people than in chat.

**Comment by codeliner** [comment]
I think this can be closed
