### ISSUE TITLE
Wrong documentation for EventStore

### ISSUE THREAD

**Issue by azngeek** [prooph/proophessor#47]
The documentation [3.2.6.1](http://getprooph.org/event-store/repositories.html) . Set Up expects an array but instead you must provide an ArrayIterator.

```
...
$this->eventStore->beginTransaction();

$this->eventStore->create(new Stream(new StreamName('event_stream'), []));

$this->eventStore->commit();
```

That would be correct.

```
$eventStore->create(new Stream(new StreamName('event_stream'), new ArrayIterator([])));
```

**Comment by prolic** [comment]
closed via https://github.com/prooph/event-store/commit/5e46312db4ea02565e5add59504c120adec35982
