### ISSUE TITLE
Can't build the docs

### ISSUE THREAD

**Issue by cdarken** [prooph/proophessor#53]
When I run `vendor/bin/bookdown docs/bookdown.json` I get this output:

```
Collecting content from docs/bookdown.json
  Added root page from docs/bookdown.json
  Collecting content from docs/book/bookdown.json
    Added index page from docs/book/bookdown.json
    Added page docs/book/prooph_in_a_nutshell.md
    Added page docs/book/components.md
    Added page docs/book/wishlist.md
  Collecting content from https://raw.githubusercontent.com/prooph/service-bus/develop/docs/bookdown.json
file_get_contents(https://raw.githubusercontent.com/prooph/service-bus/develop/docs/bookdown.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found 
```

**Comment by cdarken** [comment]
I identified the issue. In the docs/bookdown.json file, almost all the references to the other bookdown files are pointing to the develop branch while the master branch is the correct one.

**Comment by sandrokeil** [comment]
Yes, there is no develop branch anymore. Can you provide a PR please?

**Comment by codeliner** [comment]
@cdarken Do you want to work on the docs? @sandrokeil and me are currently working on a new version of the docs. We started from scratch in a separate repo here: https://github.com/sandrokeil/bookdown-template

Let me know if you want to help then we can discuss it!

**Comment by cdarken** [comment]
@sandrokeil I've created a pull request
@codeliner sorry, but I don't have the time and besides I'm trying to understand event sourcing so you can say I have my hands full

**Comment by codeliner** [comment]
@cdarken np
