### ISSUE TITLE
Fork it on Github btn does not look good on mobile or small screen size

### ISSUE THREAD

**Issue by codeliner** [prooph/proophessor#61]
The Btn added with #60 does not look good on small screens.

Shoud we hide it using media queries/bootstrap classes?

Or has someone an idea for a mobile version? Maybe move it into footer on smaller screen sizes?

**Comment by prolic** [comment]
maybe check https://codepo8.github.io/css-fork-on-github-ribbon/

**Comment by codeliner** [comment]
oh nice, I'll check it in the evening. looks promissing
