### ISSUE TITLE
Payed to Paid in tutorial image

### ISSUE THREAD

**Issue by camuthig** [prooph/proophessor#72]
The image [here](https://github.com/prooph/proophessor/blob/master/docs/tutorial/img/order_stream.png) should be updated to say "OrderPaid" instead of "OrderPayed". I didn't have a good way to update that when editing and meant to note it in the PR but forgot.

**Comment by codeliner** [comment]
good hint, I'll update it. 

FYI: images are created using [draw.io](https://www.draw.io/) and exported as xml and png. So you can simply open draw.io, import the xml, edit and export again as xml and png.
